#!/bin/bash
# Imports members from a CSV file if a CSV file is found
# This script is intended to be run by cron as root.

# absolute path of the CSV file
csvfile="/opt/pirate_feedback/member_import/member_import.csv"

# mail address(es) for report, separated by spaces
mail="pirate_feedback@example.com"


if [ ! -e $csvfile ]
then
  exit 0
fi

(

  if [ "` file -ib $csvfile `" = "text/plain; charset=utf-8" ]
  then

    cd /opt/pirate_feedback/liquid_feedback_frontend/ && \
    su www-data -c " echo \"util.import_members('$csvfile')\" | ../webmcp/bin/webmcp_shell myconfig " | \
    # remove non-printable characters, because they confuse the mail command
    tr -cd "[:print:]\n"

  else

    echo "Format of the CSV file is '` file -ib $csvfile `' instead of the expected 'text/plain; charset=utf-8'!"

  fi

  mv $csvfile $csvfile.processed_$( date +%Y-%m-%d_%H-%I-%S )

) 2>&1 | mail -s "Pirate Feedback member import report" $mail
