#!/bin/bash
# export database
# should be run by cron as user apache/www-data

# read configuration
path=$( dirname $( readlink -f $( dirname $0 ) ) )
source $path/liquid_feedback_core/config

retval=0

echo "Dropping database \"$dbname_export\" if existent ..."
dropdb "$dbname_export" 2> /dev/null
echo "Copying database \"$1\" to new database \"$EXPORT_DBNAME\" ..."
# TODO: use character encoding of original database
if (createdb "$dbname_export" && pg_dump "$dbname" | psql -f - "$dbname_export" > /dev/null)
then
  echo "Deleting private data in copied database..."
  if psql -v ON_ERROR_STOP=1 -c 'SELECT delete_private_data()' "$dbname_export" > /dev/null
  then
    echo "Dumping and compressing copied database to \"$exportfile\" ..."
    if pg_dump --no-owner --no-privileges "$dbname_export" | gzip -9 > "$exportfile"
    then
      true
    else
      retval=4
    fi
  else
    retval=3
  fi
else
  retval=2
fi

echo "Dropping database \"$dbname_export\" ..."
dropdb "$dbname_export"

echo "done"
exit $retval
