#!/bin/bash
# runs the core update routine
# will be started by /etc/init.d/lf_updated

# read configuration
path=$( dirname $( readlink -f $( dirname $0 ) ) )
source $path/liquid_feedback_core/config

PIDFILE="/var/run/lf_updated.pid"
PID=$$

if [ -f "${PIDFILE}" ] && kill -CONT $( cat "${PIDFILE}" ); then
  echo "lf_updated is already running."
  exit 1
fi

echo "${PID}" > "${PIDFILE}"

while true; do

  su - $dbuser -c "nice $path/liquid_feedback_core/lf_update dbname=$dbname 2>&1 | logger -t 'lf_updated'"

  # sleep depending on load
  sleep $( echo "5 + $( cut -f2 -d' ' < /proc/loadavg ) * 20" | bc )

done

